### ISSUE TITLE
Support `--workspace` flag

### ISSUE THREAD

**Issue by BD103** [dtolnay/cargo-docs-rs#20]
Hi! We're trying to integrate this tool into Bevy's unstable developer docs, built off of main, in https://github.com/bevyengine/bevy/pull/14350, but we're encountering one major issue.

Bevy divides code into a series of sub-crates (`bevy_ecs`, `bevy_render`, `bevy_math`, etc.), which it then re-exports in the main `bevy` crate. Because of this, we need to pass the `--workspace` flag in order for the source code to be generated for the majority of the code. 

This flag isn't supported in `cargo-docs-rs`, but it would be one of the last blockers in integrating with it.

I'd be happy to open a PR for this, I just want to make sure it fits the tool before I go through the code. :)

**Comment by dtolnay** [comment]
I would prefer not to support this in this crate. But you could look into whether someone else (or potentially an official docs.rs project) wants to maintain a more fully featured tool.

**Comment by BD103** [comment]
Ok, thank you for your time!
